### ISSUE TITLE
bug: interface with wrong return type hint

### ISSUE THREAD

**Issue by nunomaduro** [facade/ignition-contracts#5]
Hey buddies,

The https://github.com/facade/ignition-contracts/blob/1a00a6ac3760e81a3bf3519c1263bfeb4fcb756b/src/SolutionProviderRepository.php#L15 should be:

```php
* @return Solution[]
```

What do you think?

**Comment by AlexVanderbist** [comment]
Looks like this was fixed not long after this issue 😅
